CREATE VIEW VIEW_EQUIPAMENTOS AS
    SELECT 
		PREFIXO, 
		OBRA,
        CONTRATOEQUIPLOC.STATUS AS STATUS_EQUIPAMENTO_CONTRATO
		TERCEIRO.NOME as FORNECEDOR,
		TERCEIRO.INSCFEDERAL as FORNECEDOR_CNPJ,
		SISMA_MODELO.DESCRRESUM as MODELO, 
		SISMA_EQUIPAMENTO.ANOFABRI as ANO_FABRICACAO, 
		SISMA_EQUIPAMENTO.ANOMODELO as ANO_MODELO, 
		SISMA_EQUIPAMENTO.CODICONTA as DEPARTAMENTO, 
		SISMA_EQUIPAMENTO.CODICCUSTOMB as CCUSTO, 
		SISMA_EQUIPAMENTO.PLACAATUAL as PLACA,
		SISMA_EQUIPAMENTO.NUMECHAS as CHASSI,
		SISMA_EQUIPAMENTO.POTENCIAHP as POTENCIAHP,
		SISMA_FABRICANTE.DESCRICAO as FABRICANTE,
		SISMA_EQUIPAMENTO.DESCRICAO as DESCRICAO,
		SISMA_EQUIPAMENTO.ALUGUEL_CONTRATO as VALOR_LOCACAO,
		SISMA_CLASSMECAN.DESCRICAO AS CLASSEMECANICA,
		SISMA_CLASSOPERA.DESCRICAO AS CLASSEOPERACIONAL,
	FROM CONTRATOEQUIPLOC
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].EQUIPAMENTO as SISMA_EQUIPAMENTO ON CONTRATOEQUIPLOC.PREFIXO = SISMA_EQUIPAMENTO.NUMEBEM COLLATE Latin1_General_CI_AS
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].MODELO		 as SISMA_MODELO      ON SISMA_EQUIPAMENTO.IDMODE = SISMA_MODELO.IDMODE
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].FABRICANTE  as SISMA_FABRICANTE  ON SISMA_FABRICANTE.CODIFABR = SISMA_MODELO.CODIFABR
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].CLASSMECAN  as SISMA_CLASSMECAN  ON SISMA_MODELO.CODICLME = SISMA_CLASSMECAN.CODICLME
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].CLASSOPERA  as SISMA_CLASSOPERA  ON SISMA_MODELO.IDCLOP = SISMA_CLASSOPERA.IDCLOP
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].TERCEIRO as TERCEIRO ON  SISMA_EQUIPAMENTO.CODITERC = TERCEIRO.CODITERC
	WHERE PREFIXO IS NOT NULL AND PREFIXO != '';



--DROP TABLE EQUIPAMENTOS_CONTRATOS_AUXILIAR_STATUS;
CREATE TABLE EQUIPAMENTOS_CONTRATOS_AUXILIAR_STATUS {
    ID INT PRIMARY KEY NOT NULL,
    DESCRICAO varchar (50),
    OBSERVACAO varchar (255)
}
INSERT INTO  EQUIPAMENTOS_CONTRATOS_AUXILIAR_STATUS
(ID, DESCRICAO, OBSERVACAO)
VALUES
(1, 'Pendente Contrato', 'Equipamento cadastrado e disponível para seleção no processo de Contratos'),
(2, 'Contrato em Andamento com análise pendente', 'Equipamento selecionado em uma solicitação de Contrato e dispónivel no Painel de Análise do Suprimentos'),
(3, 'Contrato em Andamento com análise realizada', 'Equipamento selecionado em uma solicitação de Contrato e análise já realizada pelo Suprimentos'),
(4, 'Contrato Vigente', 'Contrato solicitado e assinado o equipamento se encontra em uso'),
(5, 'Equipamento desmobilizado', 'Aditivo realizado para desmobilização do Equipamento'),
(6, 'Contrato encerrado', 'Prazo do contrato foi encerrado e o equipamento foi devolvido para o fornecedor');

CREATE TABLE [dbo].[EQUIPAMENTOS_CONTRATOS_AUXILIAR](
	[PREFIXO] [varchar](10) NULL,
	[VALOR_MOBILIZADO] [numeric](15, 2) NULL,
	[UN_MOBILIZADO] [varchar](20) NULL,
	[VALOR_EXTRA] [numeric](15, 2) NULL,
	[UN_EXTRA] [varchar](20) NULL,
	[VALOR_FIPE] [numeric](15, 2) NULL,
	[VALOR_IMPLEMENTO] [numeric](15, 2) NULL,
	[ANALISE_REFERENCIA] [varchar](255) NULL,
	[ANALISE_OBSERVACAO] [varchar](255) NULL,
	[STATUS] [int] NULL,
	[MAODEOBRA] [decimal](18, 2) NULL,
	[ANEXOS_DOCUMENTACAO] [varchar](255) NULL,
	[ANEXOS_FOTOS] [varchar](255) NULL,
	[ANEXOS_LAUDO] [varchar](255) NULL,
	[ANEXOS_PLANO_MANUTENCAO] [varchar](255) NULL,
	[ANEXOS_ART] [varchar](255) NULL
)
ALTER TABLE EQUIPAMENTOS_CONTRATOS_AUXILIAR
ADD FOREIGN KEY (STATUS) REFERENCES EQUIPAMENTOS_CONTRATOS_AUXILIAR_STATUS(ID);



CREATE TABLE TCNT_AUXILIAR (
    CODCOLIGADA INT,
    IDCNT INT,
    IS_MODELO_CASTILHO BOOLEAN,
    TIPO_ASSINATURA VARCHAR (20),
    TIPO_CONTRATO VARCHAR (100),
    ID_FLUIG INT
);
CREATE TABLE TCNT_AUXILIAR_ITENS (
    CODCOLIGADA INT,
    IDCNT INT,
    NSEQITEMCNT INT,
    PREFIXO: VARCHAR(10),
    TIPO: VARCHAR(20),
    DESCRICAO: VARCHAR(255),
    VALOR: FLOAT,
    UN: VARCHAR
);
CREATE TABLE TCNT_AUXILIAR_HISTORICO (
    CODCOLIGADA INT,
    IDCNT INT,
    DATA: DATETIME,
    TIPO: VARCHAR(100),
    OBSERVACAO: VARCHAR(255)
);
CREATE TABLE TCNT_AUXILIAR_ASSINANTES (
    CODCOLIGADA INT,
    IDCNT INT,
    TIPO:VARCHAR(100),
    NOME:VARCHAR(255),
    CPF:INT,
    EMAIL:VARCHAR(255)
);