CREATE VIEW VIEW_EQUIPAMENTOS AS
    SELECT 
		PREFIXO, 
		OBRA,
        CONTRATOEQUIPLOC.STATUS AS STATUS_EQUIPAMENTO_CONTRATO
		TERCEIRO.NOME as FORNECEDOR,
		TERCEIRO.INSCFEDERAL as FORNECEDOR_CNPJ,
		SISMA_MODELO.DESCRRESUM as MODELO, 
		SISMA_EQUIPAMENTO.ANOFABRI as ANO_FABRICACAO, 
		SISMA_EQUIPAMENTO.ANOMODELO as ANO_MODELO, 
		SISMA_EQUIPAMENTO.CODICONTA as DEPARTAMENTO, 
		SISMA_EQUIPAMENTO.CODICCUSTOMB as CCUSTO, 
		SISMA_EQUIPAMENTO.PLACAATUAL as PLACA,
		SISMA_EQUIPAMENTO.NUMECHAS as CHASSI,
		SISMA_EQUIPAMENTO.POTENCIAHP as POTENCIAHP,
		SISMA_FABRICANTE.DESCRICAO as FABRICANTE,
		SISMA_EQUIPAMENTO.DESCRICAO as DESCRICAO,
		SISMA_EQUIPAMENTO.ALUGUEL_CONTRATO as VALOR_LOCACAO,
		SISMA_CLASSMECAN.DESCRICAO AS CLASSEMECANICA,
		SISMA_CLASSOPERA.DESCRICAO AS CLASSEOPERACIONAL,
	FROM CONTRATOEQUIPLOC
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].EQUIPAMENTO as SISMA_EQUIPAMENTO ON CONTRATOEQUIPLOC.PREFIXO = SISMA_EQUIPAMENTO.NUMEBEM COLLATE Latin1_General_CI_AS
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].MODELO		 as SISMA_MODELO      ON SISMA_EQUIPAMENTO.IDMODE = SISMA_MODELO.IDMODE
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].FABRICANTE  as SISMA_FABRICANTE  ON SISMA_FABRICANTE.CODIFABR = SISMA_MODELO.CODIFABR
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].CLASSMECAN  as SISMA_CLASSMECAN  ON SISMA_MODELO.CODICLME = SISMA_CLASSMECAN.CODICLME
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].CLASSOPERA  as SISMA_CLASSOPERA  ON SISMA_MODELO.IDCLOP = SISMA_CLASSOPERA.IDCLOP
		INNER JOIN [SQL2019].[Assiste_homologacao].[dbo].TERCEIRO as TERCEIRO ON  SISMA_EQUIPAMENTO.CODITERC = TERCEIRO.CODITERC
	WHERE PREFIXO IS NOT NULL AND PREFIXO != '';


CREATE TABLE EQUIPAMENTOS_AUXILIAR (
    PREFIXO:VARCHAR(10),
    VALOR_MOBILIZADO:DOUBLE,
    UN_MOBILIZADO:VARCHAR(5),
    VALOR_EXTRA:DOUBLE,
    UN_EXTRA:VARCHAR(5),
    VALOR_FIPE:DOUBLE,
    VALOR_IMPLEMENTO:DOUBLE,
    ANALISE_REFERENCIA:VARCHAR(255),
    ANALISE_OBSERVACAO:VARCHAR(255),
    STATUS:INT
);
CREATE TABLE TCNT_AUXILIAR (
    CODCOLIGADA INT,
    IDCNT INT,
    IS_MODELO_CASTILHO BOOLEAN,
    TIPO_ASSINATURA VARCHAR (20),
    TIPO_CONTRATO VARCHAR (100),
    ID_FLUIG INT
);
CREATE TABLE TCNT_AUXILIAR_ITENS (
    CODCOLIGADA INT,
    IDCNT INT,
    NSEQITEMCNT INT,
    PREFIXO: VARCHAR(10),
    TIPO: VARCHAR(20),
    DESCRICAO: VARCHAR(255),
    VALOR: FLOAT,
    UN: VARCHAR
);
CREATE TABLE TCNT_AUXILIAR_HISTORICO (
    CODCOLIGADA INT,
    IDCNT INT,
    DATA: DATETIME,
    TIPO: VARCHAR(100),
    OBSERVACAO: VARCHAR(255)
);
CREATE TABLE TCNT_AUXILIAR_ASSINANTES (
    CODCOLIGADA INT,
    IDCNT INT,
    TIPO:VARCHAR(100),
    NOME:VARCHAR(255),
    CPF:INT,
    EMAIL:VARCHAR(255)
);